### ISSUE TITLE
SyntaxError while loading

### ISSUE THREAD

**Issue by varac** [DarkDefender/weetweet#28]
I have weechat 2.5 from the official deb repository on Debian buster.
weetweet fails to load:

```
python: loading script "/var/data/varac/.weechat/python/autoload/weetweet.py"
python: registered script "weetweet", version 1.2.9 (Weechat twitter client)
python: stdout/stderr (weetweet): Traceback (most recent call last):  
python: stdout/stderr (weetweet):   File "/var/data/varac/.weechat/python/autoload/weetweet.py", line 1232, in oauth_proc_cb
python: stdout/stderr (weetweet):     process_output = ast.literal_eval(out)
python: stdout/stderr (weetweet):   File "/usr/lib/python2.7/ast.py", line 49, in literal_eval
python: stdout/stderr (weetweet):     node_or_string = parse(node_or_string, mode='eval')
python: stdout/stderr (weetweet):   File "/usr/lib/python2.7/ast.py", line 37, in parse
python: stdout/stderr (weetweet):     return compile(source, filename, mode, PyCF_ONLY_AST)
python: stdout/stderr (weetweet):   File "<unknown>", line 1
python: stdout/stderr (weetweet):     You need to have pkg_resources installed for version checking
python: stdout/stderr (weetweet):            ^
python: stdout/stderr (weetweet): SyntaxError: invalid syntax
⚠  python: error in function "oauth_proc_cb"
```

```
Libs:
  core:
    ncurses: 6.1 (patch 20181013)
    gcrypt: 1.8.4
    gnutls: 3.6.7
    curl: 7.64.0
    zlib: 1.2.11
  spell: aspell 0.60.7-20110707
  perl: 5.28.1
  ruby: 2.5.5
  python: 2.7.16

```
